export const STATES: Record<string, string> = {
  federal: "Federal",
  alabama: "Alabama",
  alaska: "Alaska",
  arizona: "Arizona",
  arkansas: "Arkansas",
  california: "California",
  colorado: "Colorado",
  connecticut: "Connecticut",
  delaware: "Delaware",
  florida: "Florida",
  georgia: "Georgia",
  hawaii: "Hawaii",
  idaho: "Idaho",
  illinois: "Illinois",
  indiana: "Indiana",
  iowa: "Iowa",
  kansas: "Kansas",
  kentucky: "Kentucky",
  louisiana: "Louisiana",
  maine: "Maine",
  maryland: "Maryland",
  massachusetts: "Massachusetts",
  michigan: "Michigan",
  minnesota: "Minnesota",
  mississippi: "Mississippi",
  missouri: "Missouri",
  montana: "Montana",
  nebraska: "Nebraska",
  nevada: "Nevada",
  new_hampshire: "New Hampshire",
  new_jersey: "New Jersey",
  new_mexico: "New Mexico",
  new_york: "New York",
  north_carolina: "North Carolina",
  north_dakota: "North Dakota",
  ohio: "Ohio",
  oklahoma: "Oklahoma",
  oregon: "Oregon",
  pennsylvania: "Pennsylvania",
  rhode_island: "Rhode Island",
  south_carolina: "South Carolina",
  south_dakota: "South Dakota",
  tennessee: "Tennessee",
  texas: "Texas",
  utah: "Utah",
  vermont: "Vermont",
  virginia: "Virginia",
  washington: "Washington",
  west_virginia: "West Virginia",
  wisconsin: "Wisconsin",
  wyoming: "Wyoming",
  district_of_columbia: "District of Columbia",
};

export const CATEGORIES: Record<string, string> = {
  criminal: "Criminal Law",
  civil: "Civil Law",
  family: "Family Law",
  employment: "Employment Law",
  immigration: "Immigration Law",
  intellectual_property: "Intellectual Property",
  tax: "Tax Law",
  real_estate: "Real Estate",
  bankruptcy: "Bankruptcy",
  environmental: "Environmental Law",
  constitutional: "Constitutional Law",
  corporate: "Corporate Law",
  other: "Other",
};

export const CATEGORY_ICONS: Record<string, string> = {
  criminal: "⚖️",
  civil: "📋",
  family: "👨‍👩‍👧‍👦",
  employment: "💼",
  immigration: "🌍",
  intellectual_property: "💡",
  tax: "💰",
  real_estate: "🏠",
  bankruptcy: "📉",
  environmental: "🌿",
  constitutional: "🏛️",
  corporate: "🏢",
  other: "📁",
};
